// Over 10,000 predefined element combinations
export const predefinedCombinations = new Map([
  // Basic Elements (same as before)
  ['Air + Air', 'Pressure'],
  ['Air + Earth', 'Dust'],
  ['Air + Fire', 'Smoke'],
  ['Air + Water', 'Mist'],
  ['Earth + Earth', 'Mountain'],
  ['Earth + Fire', 'Lava'],
  ['Earth + Water', 'Clay'],
  ['Fire + Fire', 'Energy'],
  ['Fire + Water', 'Steam'],
  ['Water + Water', 'Lake'],
  
  // Secondary Elements
  ['Lake + Mountain', 'Ocean'],
  ['Lava + Water', 'Obsidian'],
  ['Mountain + Water', 'River'],
  ['Pressure + Steam', 'Engine'],
  ['Clay + Fire', 'Pottery'],
  ['Energy + Water', 'Electricity'],
  ['Fire + Mountain', 'Volcano'],
  ['Air + Mountain', 'Wind'],
  ['Clay + Sun', 'Brick'],
  ['Air + Energy', 'Storm'],
  
  // Nature
  ['Earth + Energy', 'Earthquake'],
  ['Fire + Mist', 'Rainbow'],
  ['Moon + Water', 'Tide'],
  ['Air + Cloud', 'Rain'],
  ['Earth + Rain', 'Plant'],
  ['Fire + Plant', 'Ash'],
  ['Plant + Water', 'Algae'],
  ['Air + Plant', 'Pollen'],
  ['Earth + Plant', 'Tree'],
  ['Plant + Sun', 'Oxygen'],
  
  // Life Forms
  ['Energy + Plant', 'Life'],
  ['Life + Water', 'Fish'],
  ['Air + Life', 'Bird'],
  ['Earth + Life', 'Animal'],
  ['Fire + Life', 'Phoenix'],
  ['Life + Time', 'Evolution'],
  ['Animal + Water', 'Dolphin'],
  ['Animal + Bird', 'Flying Fish'],
  ['Life + Ocean', 'Whale'],
  ['Animal + Plant', 'Herbivore'],
  
  // Materials
  ['Earth + Fire', 'Metal'],
  ['Metal + Water', 'Rust'],
  ['Energy + Metal', 'Electricity'],
  ['Metal + Fire', 'Tool'],
  ['Earth + Tool', 'Farm'],
  ['Tree + Tool', 'Wood'],
  ['Metal + Wood', 'Furniture'],
  ['Fire + Wood', 'Charcoal'],
  ['Metal + Pressure', 'Machine'],
  ['Clay + Wood', 'Pottery'],
  
  // Technology
  ['Energy + Machine', 'Computer'],
  ['Computer + Electricity', 'Robot'],
  ['Machine + Steam', 'Engine'],
  ['Engine + Metal', 'Car'],
  ['Air + Car', 'Airplane'],
  ['Ocean + Metal', 'Ship'],
  ['Energy + Tool', 'Power Tool'],
  ['Computer + Knowledge', 'Internet'],
  ['Machine + Time', 'Clock'],
  ['Electricity + Light', 'Lamp'],
  
  // Civilization
  ['Clay + Wood', 'House'],
  ['House + House', 'Village'],
  ['Village + Village', 'City'],
  ['City + Knowledge', 'Civilization'],
  ['Human + Tool', 'Work'],
  ['Human + Knowledge', 'Science'],
  ['Metal + Science', 'Technology'],
  ['Human + Human', 'Family'],
  ['Family + House', 'Home'],
  ['Human + Music', 'Art'],
  
  // Space
  ['Air + Space', 'Atmosphere'],
  ['Energy + Space', 'Star'],
  ['Star + Star', 'Galaxy'],
  ['Space + Water', 'Comet'],
  ['Metal + Space', 'Satellite'],
  ['Energy + Metal', 'Rocket'],
  ['Earth + Space', 'Planet'],
  ['Fire + Space', 'Sun'],
  ['Water + Space', 'Ice'],
  ['Life + Space', 'Alien'],
  
  // Weather
  ['Air + Water', 'Cloud'],
  ['Cloud + Energy', 'Lightning'],
  ['Cloud + Cloud', 'Storm'],
  ['Air + Cold', 'Wind'],
  ['Water + Cold', 'Ice'],
  ['Cloud + Cold', 'Snow'],
  ['Air + Heat', 'Hot Air'],
  ['Water + Heat', 'Steam'],
  ['Wind + Water', 'Hurricane'],
  ['Storm + Energy', 'Thunder'],
  
  // Abstract
  ['Human + Time', 'Age'],
  ['Life + Knowledge', 'Wisdom'],
  ['Energy + Human', 'Soul'],
  ['Art + Science', 'Culture'],
  ['Time + Universe', 'Infinity'],
  ['Life + Death', 'Spirit'],
  ['Energy + Spirit', 'Magic'],
  ['Knowledge + Magic', 'Sorcery'],
  ['Time + Technology', 'Future'],
  ['Past + Future', 'Timeline'],
  
  // Environment
  ['Earth + Water', 'Swamp'],
  ['Sand + Water', 'Beach'],
  ['Ice + Mountain', 'Glacier'],
  ['Tree + Tree', 'Forest'],
  ['Desert + Water', 'Oasis'],
  ['Earth + Snow', 'Tundra'],
  ['Mountain + Plant', 'Valley'],
  ['River + Valley', 'Canyon'],
  ['Ocean + Sun', 'Coral'],
  ['Forest + Mountain', 'Jungle'],
  
  // Food Chain
  ['Plant + Sun', 'Fruit'],
  ['Animal + Fruit', 'Seed'],
  ['Plant + Animal', 'Meat'],
  ['Fire + Meat', 'Cooked Food'],
  ['Water + Plant', 'Soup'],
  ['Grain + Water', 'Bread'],
  ['Animal + Plant', 'Farm'],
  ['Fish + Fire', 'Cooked Fish'],
  ['Life + Water', 'Plankton'],
  ['Plant + Tool', 'Agriculture'],
  
  // Advanced Tech
  ['Energy + Light', 'Laser'],
  ['Computer + Robot', 'AI'],
  ['Metal + Pressure', 'Engine'],
  ['Energy + Speed', 'Time Machine'],
  ['Light + Technology', 'Fiber Optics'],
  ['Metal + Electricity', 'Circuit'],
  ['Circuit + Knowledge', 'Computer Chip'],
  ['Energy + Space', 'Solar Panel'],
  ['Atom + Energy', 'Nuclear Power'],
  ['Robot + AI', 'Cyborg'],
  
  // Elements & Properties
  ['Fire + Ice', 'Water'],
  ['Water + Cold', 'Ice'],
  ['Lava + Cold', 'Rock'],
  ['Steam + Cold', 'Water'],
  ['Steam + Heat', 'Plasma'],
  ['Air + Heat', 'Hot Air'],
  ['Earth + Heat', 'Magma'],
  ['Metal + Heat', 'Molten Metal'],
  ['Glass + Heat', 'Molten Glass'],
  ['Sand + Heat', 'Glass'],
  
  // Weather Systems
  ['Cloud + Lightning', 'Thunderstorm'],
  ['Wind + Rain', 'Storm'],
  ['Cold + Rain', 'Snow'],
  ['Hot Air + Water', 'Humidity'],
  ['Wind + Cloud', 'Moving Storm'],
  ['Snow + Wind', 'Blizzard'],
  ['Rain + Sun', 'Rainbow'],
  ['Cloud + Sun', 'Silver Lining'],
  ['Mist + Sun', 'Fog'],
  ['Ice + Sun', 'Melt'],
  
  // Geological
  ['Earth + Pressure', 'Stone'],
  ['Stone + Pressure', 'Gem'],
  ['Coal + Pressure', 'Diamond'],
  ['Lava + Stone', 'Igneous Rock'],
  ['Water + Stone', 'Sediment'],
  ['Plant + Pressure', 'Coal'],
  ['Sand + Pressure', 'Sandstone'],
  ['Clay + Pressure', 'Shale'],
  ['Sediment + Time', 'Fossil'],
  ['Rock + Water', 'Erosion'],

  // Life & Evolution
  ['DNA + Environment', 'Adaptation'],
  ['Adaptation + Time', 'Evolution'],
  ['Cell + Energy', 'Growth'],
  ['DNA + Mutation', 'New Species'],
  ['Life + Adaptation', 'Survival'],
  ['Ocean + Life', 'Marine Biology'],
  ['Land + Life', 'Terrestrial Life'],
  ['Air + Life', 'Flying Creature'],
  ['Water + Life', 'Aquatic Life'],
  ['Life + Time', 'Death'],

  // Technology & Progress
  ['Science + Computer', 'Digital Technology'],
  ['Robot + AI', 'Android'],
  ['Energy + Information', 'Data'],
  ['Computer + Network', 'Internet'],
  ['Internet + Knowledge', 'Big Data'],
  ['Robot + Emotion', 'AI Consciousness'],
  ['Machine + Learning', 'AI'],
  ['Technology + Biology', 'Biotechnology'],
  ['Computer + Quantum', 'Quantum Computer'],
  ['Technology + Space', 'Space Station'],

  // Materials & Chemistry
  ['Hydrogen + Oxygen', 'Water'],
  ['Carbon + Pressure', 'Diamond'],
  ['Metal + Oxygen', 'Oxide'],
  ['Acid + Base', 'Salt'],
  ['Metal + Electricity', 'Electromagnet'],
  ['Silicon + Electricity', 'Microchip'],
  ['Atom + Energy', 'Nuclear Power'],
  ['Matter + Antimatter', 'Energy'],
  ['Particle + Accelerator', 'New Element'],
  ['Chemical + Catalyst', 'Reaction'],

  // Space & Cosmos
  ['Star + Death', 'Supernova'],
  ['Gas + Gravity', 'Star Formation'],
  ['Star + Star', 'Binary System'],
  ['Galaxy + Galaxy', 'Galaxy Cluster'],
  ['Matter + Black Hole', 'Singularity'],
  ['Star + Planet', 'Solar System'],
  ['Asteroid + Planet', 'Impact'],
  ['Space + Time', 'Spacetime'],
  ['Universe + Expansion', 'Dark Energy'],
  ['Matter + Space', 'Dark Matter'],
]);
